import { font, hexToRgba, palette, radius, spacing, type Theme } from '@/theme';
import {
  absolute,
  centered,
  fullWidth,
  illustrationTextSizes,
  mutedSurface,
  row,
} from './tutorial-illustration-tokens';

/** Scènes « demandes », « calendar », « patients », « qr », « prescriptions » et « tournee ». */
export function buildStaffSceneStyles({ colors: c, fontSize, scale }: Theme) {
  const { text2xs, textXs } = illustrationTextSizes({ fontSize, scale });

  return {
    demandesPanel: { padding: spacing[3] },
    demandesHeader: {
      ...row,
      alignItems: 'center' as const,
      gap: spacing[2],
      marginBottom: spacing[2],
    },
    demandesAvatar: {
      width: 32,
      height: 32,
      borderRadius: radius.full,
      backgroundColor: c.primaryMid,
    },
    demandesLine: {
      flex: 1,
      height: 8,
      borderRadius: radius.full,
      backgroundColor: palette.slate[200],
    },
    demandesMap: {
      height: 64,
      borderRadius: radius.xl,
      borderWidth: 1,
      borderColor: c.primaryMid,
      backgroundColor: hexToRgba(palette.brand[50], 0.6),
    },
    actionPrimary: {
      flex: 1,
      alignItems: 'center' as const,
      borderRadius: radius.xl,
      backgroundColor: c.primary,
      paddingVertical: spacing[2.5],
    },
    actionSecondary: {
      flex: 1,
      alignItems: 'center' as const,
      borderRadius: radius.xl,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.surface,
      paddingVertical: spacing[2.5],
    },
    actionSecondaryText: { ...font.semiBold, ...textXs, color: c.textSecondary },

    calendarMonth: { ...font.semiBold, ...textXs, color: c.primaryDark },
    dayCol: { flex: 1, alignItems: 'center' as const, gap: spacing[1] },
    dayLabel: { ...font.regular, ...text2xs, color: palette.slate[400] },
    dayCell: { ...centered, width: fullWidth, height: 36, borderRadius: radius.xl },
    dayCellIdle: { borderWidth: 1, borderColor: c.borderLight, backgroundColor: mutedSurface },
    dayCellActive: { backgroundColor: c.primary },
    dayNumber: { ...font.bold, ...textXs, color: c.textSecondary },

    searchRow: {
      ...row,
      alignItems: 'center' as const,
      gap: spacing[2],
      paddingHorizontal: spacing[3],
      paddingVertical: spacing[2.5],
    },
    searchPlaceholder: { ...font.regular, ...textXs, color: palette.slate[400] },

    qrCorner: { ...absolute, width: 24, height: 24, borderColor: c.primary },
    qrCornerTopLeft: {
      left: -8,
      top: -8,
      borderTopLeftRadius: radius.lg,
      borderLeftWidth: 3,
      borderTopWidth: 3,
    },
    qrCornerTopRight: {
      right: -8,
      top: -8,
      borderTopRightRadius: radius.lg,
      borderRightWidth: 3,
      borderTopWidth: 3,
    },
    qrCornerBottomLeft: {
      left: -8,
      bottom: -8,
      borderBottomLeftRadius: radius.lg,
      borderBottomWidth: 3,
      borderLeftWidth: 3,
    },
    qrCornerBottomRight: {
      right: -8,
      bottom: -8,
      borderBottomRightRadius: radius.lg,
      borderBottomWidth: 3,
      borderRightWidth: 3,
    },
    qrFrame: {
      borderRadius: radius['2xl'],
      borderWidth: 1,
      borderColor: c.borderLight,
      backgroundColor: c.surface,
      padding: spacing[4],
    },
    qrGrid: { ...row, flexWrap: 'wrap' as const, gap: spacing[1], width: 104 },
    qrCell: { width: 12, height: 12, borderRadius: 2, backgroundColor: palette.slate[100] },
    qrCellFilled: { backgroundColor: palette.slate[900] },

    prescriptionPanel: { padding: spacing[4] },
    prescriptionHeader: { marginBottom: spacing[3] },
    prescriptionTitle: { ...font.bold, ...textXs, color: palette.slate[700] },
    textLine: { height: 8, borderRadius: radius.full, backgroundColor: palette.slate[200] },
    textLineAccent: { width: fullWidth, backgroundColor: c.primaryMid },
    textLine90: { width: '90%' as const },
    textLine75: { width: '75%' as const },
    signature: {
      marginTop: spacing[1],
      width: '45%' as const,
      height: 32,
      borderRadius: radius.lg,
      borderWidth: 1,
      borderStyle: 'dashed' as const,
      borderColor: palette.slate[300],
    },
    sentRow: {
      ...row,
      alignItems: 'center' as const,
      gap: spacing[2.5],
      borderRadius: radius['2xl'],
      borderWidth: 1,
      borderColor: palette.brand[200],
      backgroundColor: c.primaryLight,
      padding: spacing[3],
    },
    checkBadge: {
      ...centered,
      width: 32,
      height: 32,
      borderRadius: radius.full,
      backgroundColor: c.primary,
    },
    sentText: { ...font.semiBold, ...textXs, color: palette.brand[800] },

    mapCard: {
      overflow: 'hidden' as const,
      borderRadius: radius['2xl'],
      borderWidth: 1,
      borderColor: c.primaryMid,
      backgroundColor: c.primaryLight,
    },
    mapArea: { height: 72, justifyContent: 'flex-end' as const, padding: spacing[3] },
    mapPinStart: {
      ...absolute,
      left: 32,
      top: 20,
      width: 12,
      height: 12,
      borderRadius: radius.full,
      borderWidth: 2,
      borderColor: c.surface,
      backgroundColor: c.primary,
    },
    mapRoute: {
      ...absolute,
      left: 52,
      top: 32,
      width: 64,
      height: 2,
      transform: [{ rotate: '25deg' }],
      backgroundColor: palette.brand[300],
    },
    mapPinEnd: {
      ...absolute,
      right: 40,
      top: 16,
      width: 12,
      height: 12,
      borderRadius: radius.full,
      borderWidth: 2,
      borderColor: c.surface,
      backgroundColor: palette.brand[400],
    },
    mapTrack: {
      width: fullWidth,
      height: 6,
      borderRadius: radius.full,
      backgroundColor: palette.brand[200],
    },

    tourAction: {
      flex: 1,
      alignItems: 'center' as const,
      borderRadius: radius.xl,
      paddingVertical: spacing[2],
    },
    tourActionIdle: { borderWidth: 1, borderColor: c.border, backgroundColor: c.surface },
    tourActionActive: { backgroundColor: c.primary },
    tourActionText: { ...font.semiBold, ...text2xs, color: c.textSecondary },
  };
}
