import { font, hexToRgba, palette, radius, spacing, type Theme } from '@/theme';
import {
  absolute,
  centered,
  fullWidth,
  illustrationTextSizes,
  mutedSurface,
  row,
} from './tutorial-illustration-tokens';

/** Canvas, typographie et briques partagées par toutes les illustrations du tutoriel. */
export function buildBaseStyles({ colors: c, fontSize, scale, shadow }: Theme) {
  const { text2xs, textXs, textSm, textLg, textXl } = illustrationTextSizes({ fontSize, scale });

  return {
    canvas: {
      position: 'relative' as const,
      width: fullWidth,
      maxWidth: 300,
      alignSelf: 'center' as const,
    },
    canvasHaloWrap: {
      ...absolute,
      left: 0,
      right: 0,
      top: 0,
      alignItems: 'center' as const,
    },
    canvasHalo: {
      width: 120,
      height: 120,
      borderRadius: radius.full,
      backgroundColor: c.primaryLight,
      opacity: 0.9,
    },
    canvasOrbLeft: {
      ...absolute,
      left: -8,
      top: 24,
      width: 88,
      height: 88,
      borderRadius: radius.full,
      backgroundColor: c.primaryMid,
      opacity: 0.7,
    },
    canvasOrbRight: {
      ...absolute,
      right: -4,
      bottom: 16,
      width: 56,
      height: 56,
      borderRadius: radius.full,
      backgroundColor: palette.brand[200],
      opacity: 0.45,
    },
    card: {
      position: 'relative' as const,
      overflow: 'hidden' as const,
      borderRadius: radius['3xl'],
      borderWidth: 1,
      borderColor: hexToRgba(palette.brand[100], 0.8),
      backgroundColor: c.surface,
      paddingHorizontal: spacing[5],
      paddingVertical: spacing[6],
      ...shadow.md,
    },

    textInverse: { color: c.textInverse },
    titleSm: { ...font.bold, ...textSm, color: c.textPrimary },
    subtitleXs: { ...font.regular, ...textXs, color: c.textTertiary },
    captionPrimary: { ...font.semiBold, ...text2xs, color: c.primaryDark },
    badgeTextXs: { ...font.bold, ...textXs, color: c.textInverse },
    emojiXs: textXs,
    emojiSm: textSm,
    emojiLg: textLg,
    emojiXl: textXl,

    relative: { position: 'relative' as const },
    gap2: { gap: spacing[2] },
    gap3: { gap: spacing[3] },
    gap4: { gap: spacing[4] },
    flexGap1: { flex: 1, gap: spacing[1] },
    centerGap1: { alignItems: 'center' as const, gap: spacing[1] },
    centerGap2: { alignItems: 'center' as const, gap: spacing[2] },
    centerGap4: { alignItems: 'center' as const, gap: spacing[4] },
    centerGap5: { alignItems: 'center' as const, gap: spacing[5] },
    rowGap2: { ...row, gap: spacing[2] },
    rowGap1_5: { ...row, gap: spacing[1.5] },
    rowGap2_5: { ...row, gap: spacing[2.5] },
    rowWrapGap2: { ...row, flexWrap: 'wrap' as const, gap: spacing[2] },
    rowCenterGap2: { ...row, alignItems: 'center' as const, gap: spacing[2] },
    rowCenterGap3: { ...row, alignItems: 'center' as const, gap: spacing[3] },
    rowBetween: { ...row, alignItems: 'center' as const, justifyContent: 'space-between' as const },
    alignStart: { alignSelf: 'flex-start' as const },
    alignEnd: { alignSelf: 'flex-end' as const },
    mutedPanel: {
      borderRadius: radius['2xl'],
      borderWidth: 1,
      borderColor: c.borderLight,
      backgroundColor: mutedSurface,
    },

    pill: {
      borderRadius: radius.full,
      borderWidth: 1,
      paddingHorizontal: spacing[2.5],
      paddingVertical: spacing[0.5],
    },
    pillPrimary: { borderColor: palette.brand[200], backgroundColor: c.primaryLight },
    pillSuccess: { borderColor: c.successMid, backgroundColor: c.successLight },
    pillWarning: { borderColor: c.warningMid, backgroundColor: c.warningLight },
    pillText: { ...font.semiBold, ...text2xs },
    pillTextPrimary: { color: palette.brand[800] },
    pillTextSuccess: { color: palette.green[700] },
    pillTextWarning: { color: palette.amber[700] },

    avatar: {
      ...centered,
      width: 44,
      height: 44,
      borderRadius: radius['2xl'],
      backgroundColor: palette.slate[100],
    },
    avatarAccent: { backgroundColor: c.primary },
    avatarText: { ...font.bold, ...textSm, color: c.textSecondary },

    featureRow: {
      ...row,
      alignItems: 'center' as const,
      gap: spacing[3],
      borderRadius: radius['2xl'],
      borderWidth: 1,
      padding: spacing[3.5],
      borderColor: c.borderLight,
      backgroundColor: hexToRgba(mutedSurface, 0.8),
    },
    featureRowAccent: {
      borderColor: palette.brand[200],
      backgroundColor: hexToRgba(palette.brand[50], 0.8),
    },
    featureRowBody: { minWidth: 0, flex: 1, gap: spacing[1] },

    bubbleWrap: { maxWidth: '88%' as const },
    bubbleAiHeader: {
      ...row,
      alignItems: 'center' as const,
      gap: spacing[1.5],
      marginBottom: spacing[1],
    },
    bubbleAiBadge: {
      ...centered,
      width: 20,
      height: 20,
      borderRadius: radius.full,
      backgroundColor: c.primary,
    },
    bubbleAiBadgeText: { ...font.black, ...text2xs, color: c.textInverse },
    bubble: {
      borderRadius: radius['2xl'],
      paddingHorizontal: spacing[3.5],
      paddingVertical: spacing[2.5],
    },
    bubbleRight: { borderTopRightRadius: radius.sm, backgroundColor: c.primary },
    bubbleLeft: {
      borderTopLeftRadius: radius.sm,
      borderWidth: 1,
      borderColor: c.borderLight,
      backgroundColor: mutedSurface,
    },
    bubbleText: {
      ...font.regular,
      fontSize: fontSize.xs,
      lineHeight: scale(18),
      color: palette.slate[700],
    },
  };
}
