import { font, hexToRgba, palette, radius, spacing, type Theme } from '@/theme';
import {
  absolute,
  centered,
  illustrationTextSizes,
  mutedSurface,
  row,
} from './tutorial-illustration-tokens';

/** Scènes « welcome », « book », « relatives », « ai » et « notifications ». */
export function buildPatientSceneStyles({ colors: c, fontSize, scale }: Theme) {
  const { text2xs, textSm, textXs, text4xl } = illustrationTextSizes({ fontSize, scale });

  return {
    welcomeHalo: {
      ...absolute,
      top: -8,
      right: -8,
      bottom: -8,
      left: -8,
      borderRadius: radius.full,
      backgroundColor: c.primaryMid,
      opacity: 0.6,
    },
    welcomeLogo: { ...centered, width: 88, height: 88, borderRadius: 44 },
    welcomeLogoText: { ...font.black, ...text4xl, color: c.textInverse },
    welcomeDot: {
      ...absolute,
      right: -4,
      top: -4,
      width: 20,
      height: 20,
      borderRadius: radius.full,
      borderWidth: 2,
      borderColor: c.surface,
      backgroundColor: c.warning,
    },
    welcomeLinePrimary: {
      width: 140,
      height: 12,
      borderRadius: radius.full,
      backgroundColor: c.primaryMid,
    },
    welcomeLineMuted: {
      width: 100,
      height: 10,
      borderRadius: radius.full,
      backgroundColor: palette.slate[200],
    },
    welcomeTag: {
      borderRadius: radius.full,
      borderWidth: 1,
      borderColor: palette.brand[200],
      backgroundColor: c.primaryLight,
      paddingHorizontal: spacing[3],
      paddingVertical: spacing[1],
    },

    careChip: {
      alignItems: 'center' as const,
      borderRadius: radius['2xl'],
      borderWidth: 1,
      paddingHorizontal: spacing[3],
      paddingVertical: spacing[2.5],
      borderColor: c.borderLight,
      backgroundColor: mutedSurface,
    },
    careChipActive: { borderColor: c.primary, backgroundColor: c.primaryLight },
    careChipLabel: {
      marginTop: spacing[1],
      ...font.semiBold,
      ...text2xs,
      color: c.textTertiary,
    },
    progressStep: {
      flex: 1,
      height: 6,
      borderRadius: radius.full,
      backgroundColor: palette.slate[200],
    },
    progressStepDone: { backgroundColor: c.primary },
    primaryCta: {
      alignItems: 'center' as const,
      borderRadius: radius.xl,
      backgroundColor: c.primary,
      paddingVertical: spacing[3],
    },
    primaryCtaText: { ...font.bold, ...textSm, color: c.textInverse },

    addRow: {
      ...row,
      alignItems: 'center' as const,
      gap: spacing[3],
      borderRadius: radius['2xl'],
      borderWidth: 1,
      borderStyle: 'dashed' as const,
      borderColor: palette.brand[200],
      backgroundColor: hexToRgba(palette.brand[50], 0.5),
      padding: spacing[3.5],
    },
    docIcon: {
      ...centered,
      width: 44,
      height: 44,
      borderRadius: radius['2xl'],
      borderWidth: 1,
      borderColor: palette.brand[200],
      backgroundColor: c.surface,
    },
    plusBadge: {
      ...centered,
      width: 28,
      height: 28,
      borderRadius: radius.full,
      backgroundColor: c.primary,
    },

    suggestion: {
      alignSelf: 'flex-start' as const,
      borderRadius: radius['2xl'],
      borderTopLeftRadius: radius.sm,
      borderWidth: 1,
      borderColor: c.primaryMid,
      backgroundColor: c.primaryLight,
      paddingHorizontal: spacing[3.5],
      paddingVertical: spacing[2.5],
    },
    suggestionHeader: {
      ...row,
      alignItems: 'center' as const,
      gap: spacing[1],
      marginBottom: spacing[1],
    },

    bellBox: {
      ...centered,
      position: 'relative' as const,
      width: 48,
      height: 48,
      borderRadius: radius['2xl'],
      backgroundColor: c.primaryLight,
    },
    bellDot: {
      ...absolute,
      right: 4,
      top: 4,
      width: 10,
      height: 10,
      borderRadius: radius.full,
      borderWidth: 2,
      borderColor: c.surface,
      backgroundColor: c.error,
    },
    notifPanel: { gap: spacing[2], padding: spacing[3.5] },
    notifItem: { ...row, alignItems: 'flex-start' as const, gap: spacing[2.5] },
    notifItemMuted: { opacity: 0.7 },
    notifDot: {
      marginTop: spacing[0.5],
      width: 8,
      height: 8,
      borderRadius: radius.full,
      backgroundColor: c.primary,
    },
    notifDotMuted: { backgroundColor: palette.slate[300] },
    notifTitle: { ...font.bold, ...textXs, color: c.textPrimary },
    notifBody: { ...font.regular, ...text2xs, color: c.textTertiary },
    notifTitleMuted: { ...font.semiBold, ...textXs, color: palette.slate[700] },
    notifBodyMuted: { ...font.regular, ...text2xs, color: palette.slate[400] },
    hairline: { height: 1, backgroundColor: palette.slate[200] },
  };
}
