-- Seed : toutes les catégories de soins (lab + infirmiers libéraux) avec icônes Lucide
-- Les icônes sont au format Lucide (ex: bandage, syringe) ; le front ajoute le préfixe i-lucide-
-- Prérequis : exécuter la migration 021 (ADD COLUMN icon) si la colonne n'existe pas encore.

-- ========== SOINS INFIRMIERS LIBÉRAUX (nursing) ==========
-- Mise à jour des icônes pour les catégories existantes
UPDATE care_categories SET description = 'Pansements simples et complexes', icon = 'bandage' WHERE name = 'Pansement' AND type = 'nursing';
UPDATE care_categories SET description = 'Injections intramusculaires, sous-cutanées', icon = 'syringe' WHERE name = 'Injection' AND type = 'nursing';
UPDATE care_categories SET description = 'Prélèvements sanguins, urinaires', icon = 'pipette' WHERE name = 'Prélèvement' AND type = 'nursing';
UPDATE care_categories SET description = 'Pose et surveillance de perfusions', icon = 'drip' WHERE name = 'Perfusion' AND type = 'nursing';
UPDATE care_categories SET description = 'Soins de plaies chroniques ou aiguës', icon = 'circle-dot' WHERE name = 'Soins de plaies' AND type = 'nursing';

-- Insertion des soins infirmiers libéraux manquants
INSERT INTO care_categories (id, name, description, type, icon, is_active) SELECT UUID(), 'Vaccination', 'Vaccinations à domicile', 'nursing', 'syringe', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM care_categories WHERE name = 'Vaccination' AND type = 'nursing');
INSERT INTO care_categories (id, name, description, type, icon, is_active) SELECT UUID(), 'Soins post-opératoires', 'Pansements et surveillance après intervention', 'nursing', 'bandage', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM care_categories WHERE name = 'Soins post-opératoires' AND type = 'nursing');
INSERT INTO care_categories (id, name, description, type, icon, is_active) SELECT UUID(), 'Toilette / soins d''hygiène', 'Toilette et soins d''hygiène à domicile', 'nursing', 'bath', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM care_categories WHERE name = 'Toilette / soins d''hygiène' AND type = 'nursing');
INSERT INTO care_categories (id, name, description, type, icon, is_active) SELECT UUID(), 'Rééducation', 'Rééducation et mobilisation', 'nursing', 'activity', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM care_categories WHERE name = 'Rééducation' AND type = 'nursing');
INSERT INTO care_categories (id, name, description, type, icon, is_active) SELECT UUID(), 'Surveillance', 'Surveillance clinique et paramètres', 'nursing', 'stethoscope', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM care_categories WHERE name = 'Surveillance' AND type = 'nursing');
INSERT INTO care_categories (id, name, description, type, icon, is_active) SELECT UUID(), 'Soins palliatifs', 'Accompagnement et soins palliatifs', 'nursing', 'heart', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM care_categories WHERE name = 'Soins palliatifs' AND type = 'nursing');
INSERT INTO care_categories (id, name, description, type, icon, is_active) SELECT UUID(), 'Pose de cathéter', 'Pose et soins de cathéter', 'nursing', 'syringe', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM care_categories WHERE name = 'Pose de cathéter' AND type = 'nursing');
INSERT INTO care_categories (id, name, description, type, icon, is_active) SELECT UUID(), 'Prélèvement urinaire', 'Prélèvements d''urine', 'nursing', 'test-tube', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM care_categories WHERE name = 'Prélèvement urinaire' AND type = 'nursing');
INSERT INTO care_categories (id, name, description, type, icon, is_active) SELECT UUID(), 'Mesure tension / glycémie', 'Contrôle tension artérielle et glycémie', 'nursing', 'activity', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM care_categories WHERE name = 'Mesure tension / glycémie' AND type = 'nursing');
INSERT INTO care_categories (id, name, description, type, icon, is_active) SELECT UUID(), 'Aide aux repas', 'Aide à la prise des repas', 'nursing', 'utensils', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM care_categories WHERE name = 'Aide aux repas' AND type = 'nursing');
INSERT INTO care_categories (id, name, description, type, icon, is_active) SELECT UUID(), 'Garde / surveillance nuit', 'Surveillance nocturne', 'nursing', 'moon', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM care_categories WHERE name = 'Garde / surveillance nuit' AND type = 'nursing');
INSERT INTO care_categories (id, name, description, type, icon, is_active) SELECT UUID(), 'Soins de stomie', 'Soins de stomie et appareillage', 'nursing', 'circle-dot', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM care_categories WHERE name = 'Soins de stomie' AND type = 'nursing');
INSERT INTO care_categories (id, name, description, type, icon, is_active) SELECT UUID(), 'Soins de sonde', 'Soins de sonde urinaire, gastrique', 'nursing', 'circle-dot', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM care_categories WHERE name = 'Soins de sonde' AND type = 'nursing');
INSERT INTO care_categories (id, name, description, type, icon, is_active) SELECT UUID(), 'Chimiothérapie à domicile', 'Perfusion et surveillance chimiothérapie', 'nursing', 'flask-conical', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM care_categories WHERE name = 'Chimiothérapie à domicile' AND type = 'nursing');
INSERT INTO care_categories (id, name, description, type, icon, is_active) SELECT UUID(), 'Bilan de prévention', 'Bilan et prévention à domicile', 'nursing', 'clipboard-list', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM care_categories WHERE name = 'Bilan de prévention' AND type = 'nursing');
INSERT INTO care_categories (id, name, description, type, icon, is_active) SELECT UUID(), 'Soins à la personne', 'Soins généraux à la personne', 'nursing', 'user-round', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM care_categories WHERE name = 'Soins à la personne' AND type = 'nursing');
INSERT INTO care_categories (id, name, description, type, icon, is_active) SELECT UUID(), 'Injection sous-cutanée', 'Injections sous-cutanées (insuline, anticoagulants)', 'nursing', 'syringe', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM care_categories WHERE name = 'Injection sous-cutanée' AND type = 'nursing');
INSERT INTO care_categories (id, name, description, type, icon, is_active) SELECT UUID(), 'Injection intramusculaire', 'Injections intramusculaires', 'nursing', 'syringe', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM care_categories WHERE name = 'Injection intramusculaire' AND type = 'nursing');
INSERT INTO care_categories (id, name, description, type, icon, is_active) SELECT UUID(), 'Pansement complexe', 'Pansements de plaies complexes', 'nursing', 'bandage', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM care_categories WHERE name = 'Pansement complexe' AND type = 'nursing');

-- ========== PRISES DE SANG / LABORATOIRE (blood_test) ==========
-- Mise à jour des icônes pour les catégories existantes
UPDATE care_categories SET description = 'Bilan sanguin complet', icon = 'clipboard-list' WHERE name = 'Bilan complet' AND type = 'blood_test';
UPDATE care_categories SET description = 'Dosage de la glycémie', icon = 'droplet' WHERE name = 'Glycémie' AND type = 'blood_test';
UPDATE care_categories SET description = 'Dosage du cholestérol', icon = 'pill' WHERE name = 'Cholestérol' AND type = 'blood_test';
UPDATE care_categories SET description = 'Dosage des vitamines', icon = 'capsule' WHERE name = 'Vitamines' AND type = 'blood_test';
UPDATE care_categories SET description = 'Dosage hormonal', icon = 'activity' WHERE name = 'Hormones' AND type = 'blood_test';

-- Insertion des analyses labo manquantes
INSERT INTO care_categories (id, name, description, type, icon, is_active) SELECT UUID(), 'Triglycérides', 'Dosage des triglycérides', 'blood_test', 'pill', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM care_categories WHERE name = 'Triglycérides' AND type = 'blood_test');
INSERT INTO care_categories (id, name, description, type, icon, is_active) SELECT UUID(), 'NFS', 'Numération formule sanguine', 'blood_test', 'test-tube', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM care_categories WHERE name = 'NFS' AND type = 'blood_test');
INSERT INTO care_categories (id, name, description, type, icon, is_active) SELECT UUID(), 'CRP', 'Protéine C réactive (inflammation)', 'blood_test', 'test-tube', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM care_categories WHERE name = 'CRP' AND type = 'blood_test');
INSERT INTO care_categories (id, name, description, type, icon, is_active) SELECT UUID(), 'Bilan hépatique', 'ASAT, ALAT, bilirubine, gamma-GT', 'blood_test', 'flask-conical', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM care_categories WHERE name = 'Bilan hépatique' AND type = 'blood_test');
INSERT INTO care_categories (id, name, description, type, icon, is_active) SELECT UUID(), 'Bilan rénal', 'Créatinine, urée, clairance', 'blood_test', 'droplet', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM care_categories WHERE name = 'Bilan rénal' AND type = 'blood_test');
INSERT INTO care_categories (id, name, description, type, icon, is_active) SELECT UUID(), 'Fer / Ferritine', 'Bilan du fer et ferritine', 'blood_test', 'pill', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM care_categories WHERE name = 'Fer / Ferritine' AND type = 'blood_test');
INSERT INTO care_categories (id, name, description, type, icon, is_active) SELECT UUID(), 'Bilan thyroïdien', 'TSH, T3, T4', 'blood_test', 'activity', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM care_categories WHERE name = 'Bilan thyroïdien' AND type = 'blood_test');
INSERT INTO care_categories (id, name, description, type, icon, is_active) SELECT UUID(), 'Bilan lipidique', 'Cholestérol total, HDL, LDL, triglycérides', 'blood_test', 'pill', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM care_categories WHERE name = 'Bilan lipidique' AND type = 'blood_test');
INSERT INTO care_categories (id, name, description, type, icon, is_active) SELECT UUID(), 'Glycémie à jeun', 'Glycémie à jeun', 'blood_test', 'droplet', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM care_categories WHERE name = 'Glycémie à jeun' AND type = 'blood_test');
INSERT INTO care_categories (id, name, description, type, icon, is_active) SELECT UUID(), 'HbA1c', 'Hémoglobine glyquée (diabète)', 'blood_test', 'droplet', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM care_categories WHERE name = 'HbA1c' AND type = 'blood_test');
INSERT INTO care_categories (id, name, description, type, icon, is_active) SELECT UUID(), 'Bilan inflammatoire', 'Marqueurs de l''inflammation', 'blood_test', 'activity', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM care_categories WHERE name = 'Bilan inflammatoire' AND type = 'blood_test');
INSERT INTO care_categories (id, name, description, type, icon, is_active) SELECT UUID(), 'Dépistage (VIH, hépatites)', 'Sérologie VIH, hépatites B et C', 'blood_test', 'shield-check', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM care_categories WHERE name = 'Dépistage (VIH, hépatites)' AND type = 'blood_test');
INSERT INTO care_categories (id, name, description, type, icon, is_active) SELECT UUID(), 'Bilan de coagulation', 'INR, TP, TCA', 'blood_test', 'droplet', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM care_categories WHERE name = 'Bilan de coagulation' AND type = 'blood_test');
INSERT INTO care_categories (id, name, description, type, icon, is_active) SELECT UUID(), 'Bilan martial', 'Fer sérique, ferritine, transferrine', 'blood_test', 'pill', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM care_categories WHERE name = 'Bilan martial' AND type = 'blood_test');
INSERT INTO care_categories (id, name, description, type, icon, is_active) SELECT UUID(), 'Bilan vitaminique', 'Vitamines D, B12, B9, etc.', 'blood_test', 'capsule', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM care_categories WHERE name = 'Bilan vitaminique' AND type = 'blood_test');
INSERT INTO care_categories (id, name, description, type, icon, is_active) SELECT UUID(), 'Sérologie', 'Sérologies diverses', 'blood_test', 'test-tube', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM care_categories WHERE name = 'Sérologie' AND type = 'blood_test');
INSERT INTO care_categories (id, name, description, type, icon, is_active) SELECT UUID(), 'Marqueurs tumoraux', 'PSA, ACE, CA 125, etc.', 'blood_test', 'activity', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM care_categories WHERE name = 'Marqueurs tumoraux' AND type = 'blood_test');
INSERT INTO care_categories (id, name, description, type, icon, is_active) SELECT UUID(), 'Bilan pré-opératoire', 'Bilan avant intervention chirurgicale', 'blood_test', 'clipboard-list', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM care_categories WHERE name = 'Bilan pré-opératoire' AND type = 'blood_test');
INSERT INTO care_categories (id, name, description, type, icon, is_active) SELECT UUID(), 'Bilan d''anesthésie', 'Bilan pré-anesthésique', 'blood_test', 'clipboard-list', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM care_categories WHERE name = 'Bilan d''anesthésie' AND type = 'blood_test');
