export { Skeleton, SkeletonGroup } from '../Skeleton';
export {
  SkeletonAssigneeCard,
  SkeletonCareSelectionStep,
  SkeletonDashboardStats,
  SkeletonDetailActionRow,
  SkeletonDetailActionsCard,
  SkeletonEntityRow,
  SkeletonKvRow,
  SkeletonList,
  SkeletonListCard,
  SkeletonPatientAppointmentDetail,
  SkeletonPatientList,
  SkeletonPatientListRow,
  SkeletonProfileScreen,
  SkeletonRdvCarePlaceholder,
  SkeletonRdvInfoCard,
  SkeletonScreen,
  SkeletonSegmentBar,
  SkeletonStaffAppointmentDetail,
} from '../skeleton-presets';
